### ISSUE TITLE
React Workflow

### ISSUE THREAD

**Issue by detronetdip** [lego-build/community#3]
Can I add workflow for the react?

**Comment by AkpetiTrust** [comment]
Sure! You're welcome to. Just follow the instructions in the README. First fork the repo. If you are having issues contributing, just reply this comment

**Comment by detronetdip** [comment]
Great. Please assign me this issue.

**Comment by AkpetiTrust** [comment]
Done

**Comment by detronetdip** [comment]
Opening a PR soon

**Comment by Onyelaudochukwuka** [comment]
All pull requests will be merged from the 1st of october 👍🏼

**Comment by detronetdip** [comment]
Hey @AkpetiTrust  can you please tell me what the `blockName` means in the templates? will the be overwrite by user?

**Comment by Onyelaudochukwuka** [comment]
The "blockName" represents the name the  function/reducer/component/... Will  get when they're generated

**Comment by detronetdip** [comment]
Hey @Onyelaudochukwuka  I have created a pull request here #4. Please review it, as I am beginner to this project I have added the react workflow by taking the help from existing code. Please let me know what are the changes I have to make in order to make it eligible to get merge.

**Comment by detronetdip** [comment]
@AkpetiTrust  @Onyelaudochukwuka  please add hacktoberfest to your repository without it it will not be counted towards hacktoberfest.

**Comment by Onyelaudochukwuka** [comment]
Ooh I'll do that right now thanks for the heads up
